server:
  port: 80
spring:
  application:
    name: tutorial-entry
  cloud:
    nacos:
      server-addr: gonnaup.org:8848
    loadbalancer:
      nacos:
        enabled: true
    gateway:
      routes:
        - id: data-show
          uri: lb://data-show
          predicates:
            - Path=/show/**